rojo = "rojo-rbx/rojo@latest"
selene = "kampfkarren/selene@latest"
stylua = "JohnnyMorganz/stylua@latest"
tools = { wally = "UpliftGames/wally@0.3.2" }
remodel = { source = "rojo-rbx/remodel", version = "0.11.0" }