title = "Jorex"
[footer]
style = "dark"
copyright = "Copyright © 2023 LuauCoded. Built with Moonwave and Docusaurus"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "favicon"

organizationName = "LuauCoded"
projectName = "Jorex"
url = "https://LuauCoded.github.io"
baseUrl = "/Jorex"
tagline = "The Knit Alternative"

[[navbar.items]]
href = "https://www.roblox.com/users/3779554644/profile"
label = "Roblox"
position = "right"

[home]
enabled = true

[[home.features]]
title = "💪Strongly Typed "
description = ""

[[home.features]]
title = "⚡Network"
description = ""
